name: pursuit

on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: actions/cache@v2
      with:
        path: |
          output
        key: ${{ runner.os }}-build-products
    - name: generate docs
      run: nix-shell --run 'make pursuit'
    - name: upload via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "data/*"
        target: "~"
